// lib/features/recruiter/engine/scoring_engine.dart
//
// Pure-Dart port of talbotiq-platform `server/services/scoring.ts`.
// The overall score is ALWAYS recomputed here (never trusted to the model),
// exactly as the server does. Falls back to a deterministic heuristic when no
// Gemini scoring is available, so scoring works fully offline.

import '../models/recruiter_models.dart';

/// Clamp any numeric score into the inclusive 0–100 range and round to an int.
/// Shared by both the scoring and conversation engines.
int clampScore(num n) => n.clamp(0, 100).round();

/// Weighted overall — enabled-KPI weights normalized, applied to per-KPI averages.
int weightedOverall(KpiRubric rubric, Map<String, double> kpiAverages) {
  final enabled = rubric.kpis.where((k) => k.enabled && k.weight > 0).toList();
  final totalWeight = enabled.fold<double>(0, (s, k) => s + k.weight);
  if (totalWeight == 0) return 0;
  double sum = 0;
  for (final k in enabled) {
    sum += ((kpiAverages[k.id] ?? 0) * k.weight) / totalWeight;
  }
  return sum.round();
}

Map<String, double> averageKpis(
    KpiRubric rubric, List<PerQuestionResult> perQuestion) {
  final out = <String, double>{};
  for (final k in rubric.kpis.where((k) => k.enabled)) {
    final vals = perQuestion
        .map((p) => p.kpiScores[k.id])
        .whereType<double>()
        .toList();
    out[k.id] = vals.isEmpty
        ? 0
        : (vals.reduce((a, b) => a + b) / vals.length).roundToDouble();
  }
  return out;
}

String recommendationFor(int overall) {
  if (overall >= 80) return Recommendation.strongYes;
  if (overall >= 65) return Recommendation.yes;
  if (overall >= 50) return Recommendation.maybe;
  return Recommendation.no;
}

/// Keep the model's [raw] recommendation only when it's one of the recognized
/// values; otherwise derive one from the recomputed [overall] score. Shared by
/// the scoring and conversation engines (never trust an unknown label).
String resolveRecommendation(String? raw, int overall) => const [
      Recommendation.strongYes,
      Recommendation.yes,
      Recommendation.maybe,
      Recommendation.no,
    ].contains(raw)
    ? raw!
    : recommendationFor(overall);

// ── Deterministic heuristic fallback (no Gemini key) ────────────────────────

int _hash(String s) {
  int h = 2166136261;
  for (int i = 0; i < s.length; i++) {
    h ^= s.codeUnitAt(i);
    h = (h * 16777619) & 0xFFFFFFFF; // emulate Math.imul + 32-bit wrap
  }
  return h.abs();
}

int heuristicScore(String answer, String kpiId) {
  final words =
      answer.trim().split(RegExp(r'\s+')).where((w) => w.isNotEmpty).length;
  if (words == 0) return 0;
  final base = (45 + (words.clamp(0, 180) / 4).round()).clamp(0, 90);
  final key = '$kpiId:${answer.length > 40 ? answer.substring(0, 40) : answer}';
  final spread = (_hash(key) % 17) - 8;
  return clampScore(base + spread);
}

/// Fully offline report — scores reflect answer length only.
ResultReport heuristicReport(
    InterviewSession session, InterviewTemplate template) {
  final enabled = template.rubric.kpis.where((k) => k.enabled).toList();
  final perQuestion = session.questions.map((q) {
    final answer = q.answerText ?? '';
    final kpiScores = <String, double>{};
    for (final k in enabled) {
      kpiScores[k.id] = heuristicScore(answer, k.id).toDouble();
    }
    return PerQuestionResult(
      questionId: q.id,
      kpiScores: kpiScores,
      feedback: answer.trim().isNotEmpty
          ? 'Heuristic placeholder — add a Gemini key in Settings for substantive, content-aware feedback.'
          : 'No answer was provided for this question.',
    );
  }).toList();

  final kpiAverages = averageKpis(template.rubric, perQuestion);
  final overall = weightedOverall(template.rubric, kpiAverages);
  return ResultReport(
    sessionId: session.id,
    perQuestion: perQuestion,
    kpiAverages: kpiAverages,
    overallScore: overall.toDouble(),
    summary:
        'Generated by the heuristic fallback (no Gemini key configured). Scores reflect answer length only, not content quality.',
    recommendation: recommendationFor(overall),
    generatedAt: DateTime.now().toIso8601String(),
    degraded: true,
  );
}

/// Raw per-question scores as returned by a Gemini scorer (kpiId → 0-100),
/// plus feedback. Assembled into a ResultReport with a locally-computed overall.
class RawQuestionScore {
  final String questionId;
  final Map<String, double> scores;
  final String feedback;
  const RawQuestionScore(this.questionId, this.scores, this.feedback);
}

class RawScore {
  final List<RawQuestionScore> perQuestion;
  final String summary;
  final String? recommendation;
  const RawScore(
      {required this.perQuestion, required this.summary, this.recommendation});
}

ResultReport assembleFromGemini(
    InterviewSession session, InterviewTemplate template, RawScore raw) {
  final enabledIds =
      template.rubric.kpis.where((k) => k.enabled).map((k) => k.id).toSet();
  final perQuestion = session.questions.map((q) {
    RawQuestionScore? match;
    for (final p in raw.perQuestion) {
      if (p.questionId == q.id) {
        match = p;
        break;
      }
    }
    final kpiScores = <String, double>{};
    if (match != null) {
      match.scores.forEach((kpiId, score) {
        if (enabledIds.contains(kpiId)) kpiScores[kpiId] = clampScore(score).toDouble();
      });
    }
    return PerQuestionResult(
      questionId: q.id,
      kpiScores: kpiScores,
      feedback: match?.feedback ?? 'No feedback returned.',
    );
  }).toList();

  final kpiAverages = averageKpis(template.rubric, perQuestion);
  final overall = weightedOverall(template.rubric, kpiAverages);
  final rec = resolveRecommendation(raw.recommendation, overall);

  return ResultReport(
    sessionId: session.id,
    perQuestion: perQuestion,
    kpiAverages: kpiAverages,
    overallScore: overall.toDouble(),
    summary: raw.summary.isNotEmpty ? raw.summary : 'No summary returned.',
    recommendation: rec,
    generatedAt: DateTime.now().toIso8601String(),
  );
}
